# Generated by Django 6.0 on 2026-01-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_userfollows'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('ticket', 'user')},
        ),
    ]
